dist: trusty

sudo: required

language: java

jdk:
- openjdk8
- oraclejdk8

services:
- docker

env:
  global:
  # TODO make a build matrix with various mongo versions & wired tiger running only the mongo tests
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64

branches:
  only:
  - master
  - develop
  - travis

before_install:
- whoami
- id -u
- pwd
- docker version
- javac -version
- java -version

install:
- cd ..
# install elastic search
- wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.tar.gz
- tar xfz elasticsearch-5.5.0.tar.gz
- ln -s elasticsearch-5.5.0 elasticsearch

# install mongodb
- wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
- tar xfz $MONGODB_VER.tgz
- export MONGOD=`pwd`/$MONGODB_VER/bin/mongod

# install jars
- git clone https://github.com/kbase/jars

# make test config
- cd -
- echo "test.mongo.exe=$MONGOD" > test.cfg
- echo "test.elasticsearch.exe=../elasticsearch/bin/elasticsearch" >> test.cfg
- echo "test.jars.dir=../jars/lib/jars" >> test.cfg
- echo "test.temp.dir=temp_test" >> test.cfg
- echo "test.temp.dir.keep=false" >> test.cfg
- cat test.cfg

script:
- pwd
- ant compile -Djars.dir=../jars/lib/jars/
- ant test-report -Dtest.cfg=test.cfg -Djars.dir=../jars/lib/jars/

after_success:
- ls work/test-reports/
- bash <(curl -s https://codecov.io/bash) -t 206d1355-c004-4912-9921-92c6d1c003d5 -f work/test-reports/coverage-report.xml
