dist: trusty

sudo: required

language: java

jdk:
- openjdk8
- oraclejdk8

services:
- docker

notifications:
  email:
    recipients:
    - arfathpasha@gmail.com
    on_success: never
    on_failure: always

env:
  global:
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test WIRED_TIGER=false
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64
  # TEST_TOKEN
  - secure: "DC0WOpe4kkbV5QiMkhJLXpR+e1aCFHP0MPI7+adBSsEmaoIZPeN19jykD9DvATxTmlPkyRUilsMfJ+gx+P1Y4pJ0dfWsDXAgUOrf3g7QbPixEfrLBLqmY7oALcP6bKAIlZjgAtG4uFEmYJnZ9qP/5IWnzZsshJzscxxb7LWJok9hAaTs0rD5I6sHfru+/2mJnhcSE6WUhYbL88pm/3MJ0zIVoKMGPukYJY6YH6MzrMe///N5NScF6eqONFA0KVYp7PIHRAcWl82ivWhrN5Hrgq4p05+y8aq8eO8SNm4rbjayNX6Ya4zK8a5phv8zmIv0YCxlcB/e/vcLLMoXzoxZry7a7FwxCO/ao9v4kijNmOfrvp2fqRUl0OY7jQY2kMF7jowMBNoMzqweuTLohmTg2QCr/uaq6h3FxNwxesBRmHFnS4Bs3j6aQiomAuX5n+JunFG576wuFHih09dtu9ScUNr7rCOE5WCYQlsOuYFeigyv7/4iTZDr31OwwqnK48Bm+Nyw1vSp+274CjHlyCaMTSfd17kMQMVrfeRnzPSPEBQwXb98qzYxKeDEFXMKZZ5Cl+8BgxtQw5MDJ5ORiidJmfa7mewV5fK9MrIGRRZl+GTgE9MTJGpq0rEaAHtA309BbSNSXGN6VWfhj/E/sHNaqGzgRqn3PDnwu/4kPl8QVpc="
  # TEST_TOKEN2
  - secure: "UPzlmxopnwD86fGPuyd7VNt1TNGxd9IwhCbtusd8PopsxYW064uJ5Ddy8AgkzE4gms5Bb+CIGgG5w/+TukkU0MTim/iZg6us6nKKcQXYUyGeTJvGx7NuSAlKaQjfZGj6kEM/xLMFnv51XKXCzU0rdNDGIVL5mEZ9x4HvcFYIArKofPsUuh52MbsdzTy9xQszEdkigBuAX1fU0sZmpClyNSVDbiZJQmlC//z8a0jbaZAa66vhDLYK1bBDtbUvdwc8eiu6x1qKJ4lOdZAjr+oRRARJFVTckhz8lpXXExTnipFOYvLRI8woxtNMI4ZyZ2ALkr1bPz7UqJ+URlKFu4+fTxLFik/7QIGZB4Nn67oBsVTbUAESrfOqu2ihfYsRTNdkxgb6H4ubWXLjJHznIDkddLV7uX53awfd9fJ8Vik0ZjHDUwOR4xMHkux5nFZZD6hrXkXu7eg8/o6eYNpdwXylZMnf81KVYLn8KegLppIY3L5bI0rYCXrhuHcHDypI4Ir2YqE63NxWTmAg0KQW+R0d6CzMipVfbH1lwSR/eyjdPktFhjGGvehZAKE7KP+jnHG7Tdf/HTb/Jgvlggz1KqQSuouOGoqylKUJbI9fVrEpwrD3qKLc76fsSXBmE2J0EHW9mSEwODwgx5S8P17I8xUMYAnS0jAE51ErBS7zJ6AZ3s0="


branches:
  only:
  - master
  - develop
  - travis

before_install:
- whoami
- id -u
- cd ~
- pwd
- docker version
- javac -version
- java -version

install:
# install elastic search
- wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.tar.gz
- tar xfz elasticsearch-5.5.0.tar.gz
- ln -s elasticsearch-5.5.0 elasticsearch

# install mongodb
- wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
- tar xfz $MONGODB_VER.tgz
- export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
- ln -s mongodb-linux-x86_64-2.6.12 mongo

# install kb-sdk
- cd ~
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH

# install KBaseSearchEngine
- cd ~
- git clone https://github.com/arfathpasha/KBaseSearchEngine.git -b develop
- cd KBaseSearchEngine

# create test_local dir
- kb-sdk test || true

# update test.cfg with travis user
- sed -i "s/test_token=/test_token=$TEST_TOKEN\ntest.token2=$TEST_TOKEN2\n/" test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
  test_local/test.cfg
- cat test_local/test.cfg


script:
- kb-sdk test

after_success:
- ls test_local/workdir/test-reports/
- bash <(curl -s https://codecov.io/bash) -t 52a915c3-441b-4257-baa1-a1a21f0a3a74 -f test_local/workdir/test-reports/coverage-report.xml
