dist: trusty

sudo: required

language: java

jdk:
- openjdk8
- oraclejdk8

services:
- docker

notifications:
  email:
    recipients:
    - arfathpasha@gmail.com
    on_success: never
    on_failure: always

env:
  global:
  # TEST_TOKEN
  - secure: "pHsBjnrT9fOvKnmURIKEOq3k7UFvMxtEL9vzrGcaWBHyUnH3YCX94ECOKn2Ma3d8vmIEaYLDHGMjN6tMRbIlUDJQZkGuaVG+gYLSsfo0RrySxIE3ZbdI7aSnYl2f/NSKiLBDhw3/DIgDAQOCcw4rEqxb7bDd3couwFeMWn8Mzq1+tTyOnsQHxF4mHB2LnW0kXBLLMWkocqC+MyloUqRavDEdMq5H2whJiwVQFySlVM04ZKDRgpKXSZqCY3zw1cgqN3o/zo0mxOJmJP2byCicpHhsNwvEKmzayz/O2vE/FT8x3WEH/zFxzU7YPRuwcqY52ywLdB3rkPTgYNIBRO0LEqOj5PxeXT0WAaVfyyL6/t+tSyeOKdiF33/kBvQ6cAsI26MImCbO/Pm//W2f5FYGJ1BxiXtMKedzc1ENO3nJZi9pXiObARjUX2rIBOajqqUopfFTggFlZz4WoXReWj7zpZSlxX9T8vQBBBK+dfXJk0n8Za1SI0U4mVRcRcXO8DqvoUM2XbgDDR2IGqFPKQ/S0gfBuBGHMFnED0y/T6QXvF1AWqwQupN1MJzcnDm1j4wSofmFTRvHE+MtfXdm88K9OD/mcVvqSD8RyEOoLK2Vtuv4FpxHoY+9PjSPPnTjJ+GsMuMJ2jD/3Uh+clcvOfKZblAnBxEy3IswIt+SdQmK4kQ="
  # TEST_TOKEN2
  - secure: "GTFJFC0Ebs4VOVfvLNI9AqMV8O6/1gPquRWf2frlr+Igkk4X0btBk5/z1lTHXhLXuLDh88/1DxyBtkDi55PFSiTnhChS9sBrT2jHJ93EUBzL/qFBAaXmop/GUtWaPPmz0ClMBuKYTBgBAJ/tzjJNjykcIpQ4J/3rx2TgAmeZoUvNtYpzexkqTBxBfJGaJw4qO1RiF0B3m6jKHRUWW3jvY9IVDYogCh4YVjnm814AgTek05v47RqkDlpDXMSNsTWec7KRDTqQDfT+VyYrwIrE6NjdF0HymIx/Im9sAuXT1HohlBLG18zgqFy359qREoZBd/J9B91KMZkcXu/8aIh0aKGIb1eKo3oDtkXbVOnZTfWW7Qf+JPkD+xl7Q8Q1WBLcBcUocxle6NHlVKRumSNnXYPs9C7KQ+JwXoM9ms7aDG+mTEQafQJSJfLu+n0P52ho5IeKK/VISJPC9ADyxVX6290jtn4PIC029tbONa5i1YY7Ck0QLusBay5DB1qdFAHPp9xlWzMqVf9mp9cC70kPrgQcfBg4AE4KPOyE1ksJqh3Kv1IR+RIX4PJD/FnQ8G6uCG0pSoyhLGW3E1c3AkmAscmLS8ho8uc8IHGcd155M5kSzt00pfUrrNLsztHowYtyeBmgBDVehcsBMqBQ9ISZE+sk5lO+I4Vz+vxMn/L6N+4="
  - MONGODB_VER=mongodb-linux-x86_64-2.6.12 ANT_TEST=test WIRED_TIGER=false
  - JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64



branches:
  only:
  - master
  - develop
  - travis

before_install:
- whoami
- id -u
- cd ~
- pwd
- docker version
- javac -version
- java -version

install:
# install elastic search
- wget https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.5.0.tar.gz
- tar xfz elasticsearch-5.5.0.tar.gz
- ln -s elasticsearch-5.5.0 elasticsearch

# install mongodb
- wget http://fastdl.mongodb.org/linux/$MONGODB_VER.tgz
- tar xfz $MONGODB_VER.tgz
- export MONGOD=`pwd`/$MONGODB_VER/bin/mongod
- ln -s mongodb-linux-x86_64-2.6.12 mongo

# install kb-sdk
- cd ~
- git clone https://github.com/kbase/jars
- git clone https://github.com/kbase/kb_sdk
- cd kb_sdk
- make
- make sdkbase
- docker images
- export PATH=$(pwd)/bin:$PATH

# install KBaseSearchEngine
- cd ~
- git clone https://github.com/arfathpasha/KBaseSearchEngine.git -b develop
- cd KBaseSearchEngine

# create test_local dir
- kb-sdk test || true

# update test.cfg with travis user
- sed -i "s/test_token=/test_token=$TEST_TOKEN\ntest.token2=$TEST_TOKEN2\n/" test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services\https://ci.kbase.us/services\' test_local/test.cfg
- sed -i 's\https://appdev.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\https://ci.kbase.us/services/auth/api/legacy/KBase/Sessions/Login\'
  test_local/test.cfg
- cat test_local/test.cfg


script:
- kb-sdk test

after_success:
- ls test_local/workdir/test-reports/
- bash <(curl -s https://codecov.io/bash) -t 52a915c3-441b-4257-baa1-a1a21f0a3a74 -f test_local/workdir/test-reports/coverage-report.xml
